-- MySQL Script generated by MySQL Workbench
-- Thu Nov  8 21:55:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aoi_users
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aoi_users
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aoi_users` DEFAULT CHARACTER SET utf8 ;
USE `aoi_users` ;

-- -----------------------------------------------------
-- Table `aoi_users`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aoi_users`.`user` ;

CREATE TABLE IF NOT EXISTS `aoi_users`.`user` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(128) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `aoi_users`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aoi_users`.`permission` ;

CREATE TABLE IF NOT EXISTS `aoi_users`.`permission` (
  `permission_id` INT NOT NULL AUTO_INCREMENT,
  `permission_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`permission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aoi_users`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aoi_users`.`role` ;

CREATE TABLE IF NOT EXISTS `aoi_users`.`role` (
  `role_id` INT NOT NULL,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aoi_users`.`role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aoi_users`.`role_permission` ;

CREATE TABLE IF NOT EXISTS `aoi_users`.`role_permission` (
  `role_permission_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  `permission_permission_id` INT NOT NULL,
  `role_role_id` INT NOT NULL,
  PRIMARY KEY (`role_permission_id`),
  INDEX `fk_role_permission_permission_idx` (`permission_permission_id` ASC) VISIBLE,
  INDEX `fk_role_permission_role1_idx` (`role_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_permission_permission`
    FOREIGN KEY (`permission_permission_id`)
    REFERENCES `aoi_users`.`permission` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permission_role1`
    FOREIGN KEY (`role_role_id`)
    REFERENCES `aoi_users`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aoi_users`.`user_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aoi_users`.`user_permission` ;

CREATE TABLE IF NOT EXISTS `aoi_users`.`user_permission` (
  `user_permission_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  `exclusion` BIT(1) NULL,
  `permission_permission_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`user_permission_id`),
  INDEX `fk_user_permission_permission1_idx` (`permission_permission_id` ASC) VISIBLE,
  INDEX `fk_user_permission_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_permission_permission1`
    FOREIGN KEY (`permission_permission_id`)
    REFERENCES `aoi_users`.`permission` (`permission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_permission_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `aoi_users`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aoi_users`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aoi_users`.`user_role` ;

CREATE TABLE IF NOT EXISTS `aoi_users`.`user_role` (
  `user_role_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `exclusion` BIT(1) NULL,
  `role_role_id` INT NOT NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`user_role_id`),
  INDEX `fk_user_role_role1_idx` (`role_role_id` ASC) VISIBLE,
  INDEX `fk_user_role_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_role_id`)
    REFERENCES `aoi_users`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `aoi_users`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
