version: "3"
services:
        apache:
                build: ../docker-aoi-apache
                ports:
                        - "8080:80"
                networks:
                        - aoinet
        aoi:
                build: ../rest-server/
                networks:
                        - aoinet
                tty: true
        db:
                image: mysql
                networks:
                        - aoinet
                command: --default-authentication-plugin=mysql_native_password
                environment:
                        MYSQL_ROOT_PASSWORD: example
networks:
        aoinet:
