/* soapStub.h
   Generated by gSOAP 2.8.78 for cap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include <vector>
#define SOAP_NAMESPACE_OF_ns2	"http://gov.fema.ipaws.services/caprequest"
#define SOAP_NAMESPACE_OF_ns3	"http://gov.fema.ipaws.services/capresponse"
#define SOAP_NAMESPACE_OF_ns22	"urn:oasis:names:tc:emergency:cap:1.2"
#define SOAP_NAMESPACE_OF_ns1	"http://gov.fema.ipaws.services/IPAWS_CAPService/"

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20878
# error "GSOAP VERSION 20878 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumeration Types                                                          *
 *                                                                            *
\******************************************************************************/


/* cap.h:414 */
#ifndef SOAP_TYPE__ns22__alert_status
#define SOAP_TYPE__ns22__alert_status (42)
/* ns22:alert-status */
enum _ns22__alert_status {
	_ns22__alert_status__Actual = 0,
	_ns22__alert_status__Exercise = 1,
	_ns22__alert_status__System = 2,
	_ns22__alert_status__Test = 3,
	_ns22__alert_status__Draft = 4
};
#endif

/* cap.h:423 */
#ifndef SOAP_TYPE__ns22__alert_msgType
#define SOAP_TYPE__ns22__alert_msgType (44)
/* ns22:alert-msgType */
enum _ns22__alert_msgType {
	_ns22__alert_msgType__Alert = 0,
	_ns22__alert_msgType__Update = 1,
	_ns22__alert_msgType__Cancel = 2,
	_ns22__alert_msgType__Ack = 3,
	_ns22__alert_msgType__Error = 4
};
#endif

/* cap.h:434 */
#ifndef SOAP_TYPE__ns22__alert_scope
#define SOAP_TYPE__ns22__alert_scope (46)
/* ns22:alert-scope */
enum _ns22__alert_scope {
	_ns22__alert_scope__Public = 0,
	_ns22__alert_scope__Restricted = 1,
	_ns22__alert_scope__Private = 2
};
#endif

/* cap.h:472 */
#ifndef SOAP_TYPE__ns22__alert_info_category
#define SOAP_TYPE__ns22__alert_info_category (51)
/* ns22:alert-info-category */
enum _ns22__alert_info_category {
	_ns22__alert_info_category__Geo = 0,
	_ns22__alert_info_category__Met = 1,
	_ns22__alert_info_category__Safety = 2,
	_ns22__alert_info_category__Security = 3,
	_ns22__alert_info_category__Rescue = 4,
	_ns22__alert_info_category__Fire = 5,
	_ns22__alert_info_category__Health = 6,
	_ns22__alert_info_category__Env = 7,
	_ns22__alert_info_category__Transport = 8,
	_ns22__alert_info_category__Infra = 9,
	_ns22__alert_info_category__CBRNE = 10,
	_ns22__alert_info_category__Other = 11
};
#endif

/* cap.h:492 */
#ifndef SOAP_TYPE__ns22__alert_info_responseType
#define SOAP_TYPE__ns22__alert_info_responseType (54)
/* ns22:alert-info-responseType */
enum _ns22__alert_info_responseType {
	_ns22__alert_info_responseType__Shelter = 0,
	_ns22__alert_info_responseType__Evacuate = 1,
	_ns22__alert_info_responseType__Prepare = 2,
	_ns22__alert_info_responseType__Execute = 3,
	_ns22__alert_info_responseType__Avoid = 4,
	_ns22__alert_info_responseType__Monitor = 5,
	_ns22__alert_info_responseType__Assess = 6,
	_ns22__alert_info_responseType__AllClear = 7,
	_ns22__alert_info_responseType__None = 8
};
#endif

/* cap.h:505 */
#ifndef SOAP_TYPE__ns22__alert_info_urgency
#define SOAP_TYPE__ns22__alert_info_urgency (57)
/* ns22:alert-info-urgency */
enum _ns22__alert_info_urgency {
	_ns22__alert_info_urgency__Immediate = 0,
	_ns22__alert_info_urgency__Expected = 1,
	_ns22__alert_info_urgency__Future = 2,
	_ns22__alert_info_urgency__Past = 3,
	_ns22__alert_info_urgency__Unknown = 4
};
#endif

/* cap.h:514 */
#ifndef SOAP_TYPE__ns22__alert_info_severity
#define SOAP_TYPE__ns22__alert_info_severity (59)
/* ns22:alert-info-severity */
enum _ns22__alert_info_severity {
	_ns22__alert_info_severity__Extreme = 0,
	_ns22__alert_info_severity__Severe = 1,
	_ns22__alert_info_severity__Moderate = 2,
	_ns22__alert_info_severity__Minor = 3,
	_ns22__alert_info_severity__Unknown = 4
};
#endif

/* cap.h:523 */
#ifndef SOAP_TYPE__ns22__alert_info_certainty
#define SOAP_TYPE__ns22__alert_info_certainty (61)
/* ns22:alert-info-certainty */
enum _ns22__alert_info_certainty {
	_ns22__alert_info_certainty__Observed = 0,
	_ns22__alert_info_certainty__Likely = 1,
	_ns22__alert_info_certainty__Possible = 2,
	_ns22__alert_info_certainty__Unlikely = 3,
	_ns22__alert_info_certainty__Unknown = 4
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

class ns2__requestParameterList;	/* cap.h:182 */
class ns2__parameterListItem;	/* cap.h:184 */
class ns3__responseParameterList;	/* cap.h:186 */
class ns3__subParameterListItem;	/* cap.h:188 */
class _ns3__parameterListItem;	/* cap.h:190 */
class _ns22__alert_info_eventCode;	/* cap.h:546 */
class _ns22__alert_info_parameter;	/* cap.h:587 */
class _ns22__alert_info_resource;	/* cap.h:607 */
class _ns22__alert_info_area_geocode;	/* cap.h:656 */
class _ns22__alert_info_area;	/* cap.h:635 */
class _ns22__alert_info;	/* cap.h:465 */
class _ns22__alert;	/* cap.h:192 */
class _ns1__postCAPRequestTypeDef;	/* cap.h:194 */
class _ns1__CAPServiceException;	/* cap.h:196 */
class _ns1__postCAPResponseTypeDef;	/* cap.h:198 */
class _ns1__messageResponseTypeDef;	/* cap.h:200 */
class _ns1__CAPHeaderTypeDef;	/* cap.h:202 */
struct __ns1__getRequest;	/* cap.h:1076 */
struct __ns1__postCAP;	/* cap.h:1153 */
struct __ns1__getMessage;	/* cap.h:1230 */

/* cap.h:182 */
#ifndef SOAP_TYPE_ns2__requestParameterList
#define SOAP_TYPE_ns2__requestParameterList (15)
/* complex XML schema type 'ns2:requestParameterList': */
class SOAP_CMAC ns2__requestParameterList {
      public:
        /// Optional element 'ns2:requestAPI' of XML schema type 'xsd:string'
        std::string *requestAPI;
        /// Optional element 'ns2:requestOperation' of XML schema type 'xsd:string'
        std::string *requestOperation;
        /// Optional element 'ns2:parameters' of XML schema type 'ns2:parameterListItem'
        std::vector<ns2__parameterListItem *> parameters;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns2__requestParameterList
        virtual long soap_type(void) const { return SOAP_TYPE_ns2__requestParameterList; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns2__requestParameterList, default initialized and not managed by a soap context
        virtual ns2__requestParameterList *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(ns2__requestParameterList); }
      public:
        /// Constructor with default initializations
        ns2__requestParameterList() : requestAPI(), requestOperation(), parameters(), soap() { }
        virtual ~ns2__requestParameterList() { }
        /// Friend allocator used by soap_new_ns2__requestParameterList(struct soap*, int)
        friend SOAP_FMAC1 ns2__requestParameterList * SOAP_FMAC2 soap_instantiate_ns2__requestParameterList(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:184 */
#ifndef SOAP_TYPE_ns2__parameterListItem
#define SOAP_TYPE_ns2__parameterListItem (17)
/* complex XML schema type 'ns2:parameterListItem': */
class SOAP_CMAC ns2__parameterListItem {
      public:
        /// Optional element 'ns2:parameterName' of XML schema type 'xsd:string'
        std::string *parameterName;
        /// Optional element 'ns2:comparisonOp' of XML schema type 'xsd:string'
        std::string *comparisonOp;
        /// Optional element 'ns2:parameterValue' of XML schema type 'xsd:string'
        std::vector<std::string> parameterValue;
        /// Optional element 'ns2:logicalOp' of XML schema type 'xsd:string'
        std::string *logicalOp;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns2__parameterListItem
        virtual long soap_type(void) const { return SOAP_TYPE_ns2__parameterListItem; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns2__parameterListItem, default initialized and not managed by a soap context
        virtual ns2__parameterListItem *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(ns2__parameterListItem); }
      public:
        /// Constructor with default initializations
        ns2__parameterListItem() : parameterName(), comparisonOp(), parameterValue(), logicalOp(), soap() { }
        virtual ~ns2__parameterListItem() { }
        /// Friend allocator used by soap_new_ns2__parameterListItem(struct soap*, int)
        friend SOAP_FMAC1 ns2__parameterListItem * SOAP_FMAC2 soap_instantiate_ns2__parameterListItem(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:186 */
#ifndef SOAP_TYPE_ns3__responseParameterList
#define SOAP_TYPE_ns3__responseParameterList (19)
/* complex XML schema type 'ns3:responseParameterList': */
class SOAP_CMAC ns3__responseParameterList {
      public:
        /// Optional element 'ns3:parameterListItem' of XML schema type 'ns3:parameterListItem'
        std::vector<_ns3__parameterListItem *> parameterListItem;
        /// Optional element 'ns3:ResponseOperation' of XML schema type 'xsd:string'
        std::string *ResponseOperation;
        /// Optional element 'ns3:ResponseType' of XML schema type 'xsd:string'
        std::string *ResponseType;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns3__responseParameterList
        virtual long soap_type(void) const { return SOAP_TYPE_ns3__responseParameterList; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns3__responseParameterList, default initialized and not managed by a soap context
        virtual ns3__responseParameterList *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(ns3__responseParameterList); }
      public:
        /// Constructor with default initializations
        ns3__responseParameterList() : parameterListItem(), ResponseOperation(), ResponseType(), soap() { }
        virtual ~ns3__responseParameterList() { }
        /// Friend allocator used by soap_new_ns3__responseParameterList(struct soap*, int)
        friend SOAP_FMAC1 ns3__responseParameterList * SOAP_FMAC2 soap_instantiate_ns3__responseParameterList(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:188 */
#ifndef SOAP_TYPE_ns3__subParameterListItem
#define SOAP_TYPE_ns3__subParameterListItem (21)
/* complex XML schema type 'ns3:subParameterListItem': */
class SOAP_CMAC ns3__subParameterListItem {
      public:
        /// Optional element 'ns3:subParameterName' of XML schema type 'xsd:string'
        std::string *subParameterName;
        /// Optional element 'ns3:subParameterValue' of XML schema type 'xsd:string'
        std::string *subParameterValue;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE_ns3__subParameterListItem
        virtual long soap_type(void) const { return SOAP_TYPE_ns3__subParameterListItem; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type ns3__subParameterListItem, default initialized and not managed by a soap context
        virtual ns3__subParameterListItem *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(ns3__subParameterListItem); }
      public:
        /// Constructor with default initializations
        ns3__subParameterListItem() : subParameterName(), subParameterValue(), soap() { }
        virtual ~ns3__subParameterListItem() { }
        /// Friend allocator used by soap_new_ns3__subParameterListItem(struct soap*, int)
        friend SOAP_FMAC1 ns3__subParameterListItem * SOAP_FMAC2 soap_instantiate_ns3__subParameterListItem(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:190 */
#ifndef SOAP_TYPE__ns3__parameterListItem
#define SOAP_TYPE__ns3__parameterListItem (23)
/* complex XML schema type 'ns3:parameterListItem': */
class SOAP_CMAC _ns3__parameterListItem {
      public:
        /// Optional element 'ns3:parameterName' of XML schema type 'xsd:string'
        std::string *parameterName;
        /// Optional element 'ns3:parameterValue' of XML schema type 'xsd:string'
        std::string *parameterValue;
        /// Optional element 'ns3:subParaListItem' of XML schema type 'ns3:subParameterListItem'
        std::vector<ns3__subParameterListItem *> subParaListItem;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns3__parameterListItem
        virtual long soap_type(void) const { return SOAP_TYPE__ns3__parameterListItem; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns3__parameterListItem, default initialized and not managed by a soap context
        virtual _ns3__parameterListItem *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns3__parameterListItem); }
      public:
        /// Constructor with default initializations
        _ns3__parameterListItem() : parameterName(), parameterValue(), subParaListItem(), soap() { }
        virtual ~_ns3__parameterListItem() { }
        /// Friend allocator used by soap_new__ns3__parameterListItem(struct soap*, int)
        friend SOAP_FMAC1 _ns3__parameterListItem * SOAP_FMAC2 soap_instantiate__ns3__parameterListItem(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:546 */
#ifndef SOAP_TYPE__ns22__alert_info_eventCode
#define SOAP_TYPE__ns22__alert_info_eventCode (63)
/* complex XML schema type 'ns22:alert-info-eventCode': */
class SOAP_CMAC _ns22__alert_info_eventCode {
      public:
        /// Required element 'ns22:valueName' of XML schema type 'xsd:string'
        std::string valueName;
        /// Required element 'ns22:value' of XML schema type 'xsd:string'
        std::string value;
      public:
        /// Return unique type id SOAP_TYPE__ns22__alert_info_eventCode
        virtual long soap_type(void) const { return SOAP_TYPE__ns22__alert_info_eventCode; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns22__alert_info_eventCode, default initialized and not managed by a soap context
        virtual _ns22__alert_info_eventCode *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns22__alert_info_eventCode); }
      public:
        /// Constructor with default initializations
        _ns22__alert_info_eventCode() : valueName(), value() { }
        virtual ~_ns22__alert_info_eventCode() { }
        /// Friend allocator used by soap_new__ns22__alert_info_eventCode(struct soap*, int)
        friend SOAP_FMAC1 _ns22__alert_info_eventCode * SOAP_FMAC2 soap_instantiate__ns22__alert_info_eventCode(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:587 */
#ifndef SOAP_TYPE__ns22__alert_info_parameter
#define SOAP_TYPE__ns22__alert_info_parameter (68)
/* complex XML schema type 'ns22:alert-info-parameter': */
class SOAP_CMAC _ns22__alert_info_parameter {
      public:
        /// Required element 'ns22:valueName' of XML schema type 'xsd:string'
        std::string valueName;
        /// Required element 'ns22:value' of XML schema type 'xsd:string'
        std::string value;
      public:
        /// Return unique type id SOAP_TYPE__ns22__alert_info_parameter
        virtual long soap_type(void) const { return SOAP_TYPE__ns22__alert_info_parameter; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns22__alert_info_parameter, default initialized and not managed by a soap context
        virtual _ns22__alert_info_parameter *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns22__alert_info_parameter); }
      public:
        /// Constructor with default initializations
        _ns22__alert_info_parameter() : valueName(), value() { }
        virtual ~_ns22__alert_info_parameter() { }
        /// Friend allocator used by soap_new__ns22__alert_info_parameter(struct soap*, int)
        friend SOAP_FMAC1 _ns22__alert_info_parameter * SOAP_FMAC2 soap_instantiate__ns22__alert_info_parameter(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:607 */
#ifndef SOAP_TYPE__ns22__alert_info_resource
#define SOAP_TYPE__ns22__alert_info_resource (71)
/* complex XML schema type 'ns22:alert-info-resource': */
class SOAP_CMAC _ns22__alert_info_resource {
      public:
        /// Required element 'ns22:resourceDesc' of XML schema type 'xsd:string'
        std::string resourceDesc;
        /// Required element 'ns22:mimeType' of XML schema type 'xsd:string'
        std::string mimeType;
        /// Optional element 'ns22:size' of XML schema type 'xsd:integer'
        std::string *size;
        /// Optional element 'ns22:uri' of XML schema type 'xsd:anyURI'
        std::string *uri;
        /// Optional element 'ns22:derefUri' of XML schema type 'xsd:string'
        std::string *derefUri;
        /// Optional element 'ns22:digest' of XML schema type 'xsd:string'
        std::string *digest;
      public:
        /// Return unique type id SOAP_TYPE__ns22__alert_info_resource
        virtual long soap_type(void) const { return SOAP_TYPE__ns22__alert_info_resource; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns22__alert_info_resource, default initialized and not managed by a soap context
        virtual _ns22__alert_info_resource *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns22__alert_info_resource); }
      public:
        /// Constructor with default initializations
        _ns22__alert_info_resource() : resourceDesc(), mimeType(), size(), uri(), derefUri(), digest() { }
        virtual ~_ns22__alert_info_resource() { }
        /// Friend allocator used by soap_new__ns22__alert_info_resource(struct soap*, int)
        friend SOAP_FMAC1 _ns22__alert_info_resource * SOAP_FMAC2 soap_instantiate__ns22__alert_info_resource(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:656 */
#ifndef SOAP_TYPE__ns22__alert_info_area_geocode
#define SOAP_TYPE__ns22__alert_info_area_geocode (77)
/* complex XML schema type 'ns22:alert-info-area-geocode': */
class SOAP_CMAC _ns22__alert_info_area_geocode {
      public:
        /// Required element 'ns22:valueName' of XML schema type 'xsd:string'
        std::string valueName;
        /// Required element 'ns22:value' of XML schema type 'xsd:string'
        std::string value;
      public:
        /// Return unique type id SOAP_TYPE__ns22__alert_info_area_geocode
        virtual long soap_type(void) const { return SOAP_TYPE__ns22__alert_info_area_geocode; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns22__alert_info_area_geocode, default initialized and not managed by a soap context
        virtual _ns22__alert_info_area_geocode *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns22__alert_info_area_geocode); }
      public:
        /// Constructor with default initializations
        _ns22__alert_info_area_geocode() : valueName(), value() { }
        virtual ~_ns22__alert_info_area_geocode() { }
        /// Friend allocator used by soap_new__ns22__alert_info_area_geocode(struct soap*, int)
        friend SOAP_FMAC1 _ns22__alert_info_area_geocode * SOAP_FMAC2 soap_instantiate__ns22__alert_info_area_geocode(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:635 */
#ifndef SOAP_TYPE__ns22__alert_info_area
#define SOAP_TYPE__ns22__alert_info_area (75)
/* complex XML schema type 'ns22:alert-info-area': */
class SOAP_CMAC _ns22__alert_info_area {
      public:
        /// Required element 'ns22:areaDesc' of XML schema type 'xsd:string'
        std::string areaDesc;
        /// Optional element 'ns22:polygon' of XML schema type 'xsd:string'
        std::vector<std::string> polygon;
        /// Optional element 'ns22:circle' of XML schema type 'xsd:string'
        std::vector<std::string> circle;
        /// Optional element 'ns22:geocode' of XML schema type 'ns22:alert-info-area-geocode'
        std::vector<_ns22__alert_info_area_geocode> geocode;
        /// Optional element 'ns22:altitude' of XML schema type 'xsd:decimal'
        std::string *altitude;
        /// Optional element 'ns22:ceiling' of XML schema type 'xsd:decimal'
        std::string *ceiling;
      public:
        /// Return unique type id SOAP_TYPE__ns22__alert_info_area
        virtual long soap_type(void) const { return SOAP_TYPE__ns22__alert_info_area; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns22__alert_info_area, default initialized and not managed by a soap context
        virtual _ns22__alert_info_area *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns22__alert_info_area); }
      public:
        /// Constructor with default initializations
        _ns22__alert_info_area() : areaDesc(), polygon(), circle(), geocode(), altitude(), ceiling() { }
        virtual ~_ns22__alert_info_area() { }
        /// Friend allocator used by soap_new__ns22__alert_info_area(struct soap*, int)
        friend SOAP_FMAC1 _ns22__alert_info_area * SOAP_FMAC2 soap_instantiate__ns22__alert_info_area(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:465 */
#ifndef SOAP_TYPE__ns22__alert_info
#define SOAP_TYPE__ns22__alert_info (48)
/* complex XML schema type 'ns22:alert-info': */
class SOAP_CMAC _ns22__alert_info {
      public:
        /// Optional element 'ns22:language' of XML schema type 'xsd:language'
        std::string *language;	///< optional with default value = "en-US"
        /// Required element 'ns22:category' of XML schema type 'ns22:alert-info-category'
        std::vector<enum _ns22__alert_info_category> category;
        /// Required element 'ns22:event' of XML schema type 'xsd:string'
        std::string event;
        /// Optional element 'ns22:responseType' of XML schema type 'ns22:alert-info-responseType'
        std::vector<enum _ns22__alert_info_responseType> responseType;
        /// Required element 'ns22:urgency' of XML schema type 'ns22:alert-info-urgency'
        enum _ns22__alert_info_urgency urgency;
        /// Required element 'ns22:severity' of XML schema type 'ns22:alert-info-severity'
        enum _ns22__alert_info_severity severity;
        /// Required element 'ns22:certainty' of XML schema type 'ns22:alert-info-certainty'
        enum _ns22__alert_info_certainty certainty;
        /// Optional element 'ns22:audience' of XML schema type 'xsd:string'
        std::string *audience;
        /// Optional element 'ns22:eventCode' of XML schema type 'ns22:alert-info-eventCode'
        std::vector<_ns22__alert_info_eventCode> eventCode;
        /// Optional element 'ns22:effective' of XML schema type 'xsd:dateTime'
        time_t *effective;
        /// Optional element 'ns22:onset' of XML schema type 'xsd:dateTime'
        time_t *onset;
        /// Optional element 'ns22:expires' of XML schema type 'xsd:dateTime'
        time_t *expires;
        /// Optional element 'ns22:senderName' of XML schema type 'xsd:string'
        std::string *senderName;
        /// Optional element 'ns22:headline' of XML schema type 'xsd:string'
        std::string *headline;
        /// Optional element 'ns22:description' of XML schema type 'xsd:string'
        std::string *description;
        /// Optional element 'ns22:instruction' of XML schema type 'xsd:string'
        std::string *instruction;
        /// Optional element 'ns22:web' of XML schema type 'xsd:anyURI'
        std::string *web;
        /// Optional element 'ns22:contact' of XML schema type 'xsd:string'
        std::string *contact;
        /// Optional element 'ns22:parameter' of XML schema type 'ns22:alert-info-parameter'
        std::vector<_ns22__alert_info_parameter> parameter;
        /// Optional element 'ns22:resource' of XML schema type 'ns22:alert-info-resource'
        std::vector<_ns22__alert_info_resource> resource;
        /// Optional element 'ns22:area' of XML schema type 'ns22:alert-info-area'
        std::vector<_ns22__alert_info_area> area;
      public:
        /// Return unique type id SOAP_TYPE__ns22__alert_info
        virtual long soap_type(void) const { return SOAP_TYPE__ns22__alert_info; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns22__alert_info, default initialized and not managed by a soap context
        virtual _ns22__alert_info *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns22__alert_info); }
      public:
        /// Constructor with default initializations
        _ns22__alert_info() : language(), category(), event(), responseType(), urgency(), severity(), certainty(), audience(), eventCode(), effective(), onset(), expires(), senderName(), headline(), description(), instruction(), web(), contact(), parameter(), resource(), area() { }
        virtual ~_ns22__alert_info() { }
        /// Friend allocator used by soap_new__ns22__alert_info(struct soap*, int)
        friend SOAP_FMAC1 _ns22__alert_info * SOAP_FMAC2 soap_instantiate__ns22__alert_info(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:192 */
#ifndef SOAP_TYPE__ns22__alert
#define SOAP_TYPE__ns22__alert (25)
/* complex XML schema type 'ns22:alert': */
class SOAP_CMAC _ns22__alert {
      public:
        /// Required element 'ns22:identifier' of XML schema type 'xsd:string'
        std::string identifier;
        /// Required element 'ns22:sender' of XML schema type 'xsd:string'
        std::string sender;
        /// Required element 'ns22:sent' of XML schema type 'xsd:dateTime'
        time_t sent;
        /// Required element 'ns22:status' of XML schema type 'ns22:alert-status'
        enum _ns22__alert_status status;
        /// Required element 'ns22:msgType' of XML schema type 'ns22:alert-msgType'
        enum _ns22__alert_msgType msgType;
        /// Optional element 'ns22:source' of XML schema type 'xsd:string'
        std::string *source;
        /// Required element 'ns22:scope' of XML schema type 'ns22:alert-scope'
        enum _ns22__alert_scope scope;
        /// Optional element 'ns22:restriction' of XML schema type 'xsd:string'
        std::string *restriction;
        /// Optional element 'ns22:addresses' of XML schema type 'xsd:string'
        std::string *addresses;
        /// Optional element 'ns22:code' of XML schema type 'xsd:string'
        std::vector<std::string> code;
        /// Optional element 'ns22:note' of XML schema type 'xsd:string'
        std::string *note;
        /// Optional element 'ns22:references' of XML schema type 'xsd:string'
        std::string *references;
        /// Optional element 'ns22:incidents' of XML schema type 'xsd:string'
        std::string *incidents;
        /// Optional element 'ns22:info' of XML schema type 'ns22:alert-info'
        std::vector<_ns22__alert_info> info;
        std::vector<char *> __any;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns22__alert
        virtual long soap_type(void) const { return SOAP_TYPE__ns22__alert; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns22__alert, default initialized and not managed by a soap context
        virtual _ns22__alert *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns22__alert); }
      public:
        /// Constructor with default initializations
        _ns22__alert() : identifier(), sender(), sent(), status(), msgType(), source(), scope(), restriction(), addresses(), code(), note(), references(), incidents(), info(), __any(), soap() { }
        virtual ~_ns22__alert() { }
        /// Friend allocator used by soap_new__ns22__alert(struct soap*, int)
        friend SOAP_FMAC1 _ns22__alert * SOAP_FMAC2 soap_instantiate__ns22__alert(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:194 */
#ifndef SOAP_TYPE__ns1__postCAPRequestTypeDef
#define SOAP_TYPE__ns1__postCAPRequestTypeDef (27)
/* complex XML schema type 'ns1:postCAPRequestTypeDef': */
class SOAP_CMAC _ns1__postCAPRequestTypeDef {
      public:
        /// Required element 'ns22:alert' of XML schema type 'ns22:alert'
        _ns22__alert *ns22__alert;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns1__postCAPRequestTypeDef
        virtual long soap_type(void) const { return SOAP_TYPE__ns1__postCAPRequestTypeDef; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns1__postCAPRequestTypeDef, default initialized and not managed by a soap context
        virtual _ns1__postCAPRequestTypeDef *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns1__postCAPRequestTypeDef); }
      public:
        /// Constructor with default initializations
        _ns1__postCAPRequestTypeDef() : ns22__alert(), soap() { }
        virtual ~_ns1__postCAPRequestTypeDef() { }
        /// Friend allocator used by soap_new__ns1__postCAPRequestTypeDef(struct soap*, int)
        friend SOAP_FMAC1 _ns1__postCAPRequestTypeDef * SOAP_FMAC2 soap_instantiate__ns1__postCAPRequestTypeDef(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:196 */
#ifndef SOAP_TYPE__ns1__CAPServiceException
#define SOAP_TYPE__ns1__CAPServiceException (29)
/* complex XML schema type 'ns1:CAPServiceException': */
class SOAP_CMAC _ns1__CAPServiceException {
      public:
        /// Required nillable (xsi:nil when NULL) element 'ns1:errorCode' of XML schema type 'xsd:string'
        std::string *errorCode;
        /// Required nillable (xsi:nil when NULL) element 'ns1:message' of XML schema type 'xsd:string'
        std::string *message;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns1__CAPServiceException
        virtual long soap_type(void) const { return SOAP_TYPE__ns1__CAPServiceException; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns1__CAPServiceException, default initialized and not managed by a soap context
        virtual _ns1__CAPServiceException *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns1__CAPServiceException); }
      public:
        /// Constructor with default initializations
        _ns1__CAPServiceException() : errorCode(), message(), soap() { }
        virtual ~_ns1__CAPServiceException() { }
        /// Friend allocator used by soap_new__ns1__CAPServiceException(struct soap*, int)
        friend SOAP_FMAC1 _ns1__CAPServiceException * SOAP_FMAC2 soap_instantiate__ns1__CAPServiceException(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:198 */
#ifndef SOAP_TYPE__ns1__postCAPResponseTypeDef
#define SOAP_TYPE__ns1__postCAPResponseTypeDef (31)
/* complex XML schema type 'ns1:postCAPResponseTypeDef': */
class SOAP_CMAC _ns1__postCAPResponseTypeDef {
      public:
        /// Required nillable (xsi:nil when NULL) element 'ns1:postCAPReturn' of XML schema type 'xsd:string'
        std::string *postCAPReturn;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns1__postCAPResponseTypeDef
        virtual long soap_type(void) const { return SOAP_TYPE__ns1__postCAPResponseTypeDef; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns1__postCAPResponseTypeDef, default initialized and not managed by a soap context
        virtual _ns1__postCAPResponseTypeDef *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns1__postCAPResponseTypeDef); }
      public:
        /// Constructor with default initializations
        _ns1__postCAPResponseTypeDef() : postCAPReturn(), soap() { }
        virtual ~_ns1__postCAPResponseTypeDef() { }
        /// Friend allocator used by soap_new__ns1__postCAPResponseTypeDef(struct soap*, int)
        friend SOAP_FMAC1 _ns1__postCAPResponseTypeDef * SOAP_FMAC2 soap_instantiate__ns1__postCAPResponseTypeDef(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:200 */
#ifndef SOAP_TYPE__ns1__messageResponseTypeDef
#define SOAP_TYPE__ns1__messageResponseTypeDef (33)
/* complex XML schema type 'ns1:messageResponseTypeDef': */
class SOAP_CMAC _ns1__messageResponseTypeDef {
      public:
        /// Optional element 'ns22:alert' of XML schema type 'ns22:alert'
        std::vector<_ns22__alert *> ns22__alert;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns1__messageResponseTypeDef
        virtual long soap_type(void) const { return SOAP_TYPE__ns1__messageResponseTypeDef; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns1__messageResponseTypeDef, default initialized and not managed by a soap context
        virtual _ns1__messageResponseTypeDef *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns1__messageResponseTypeDef); }
      public:
        /// Constructor with default initializations
        _ns1__messageResponseTypeDef() : ns22__alert(), soap() { }
        virtual ~_ns1__messageResponseTypeDef() { }
        /// Friend allocator used by soap_new__ns1__messageResponseTypeDef(struct soap*, int)
        friend SOAP_FMAC1 _ns1__messageResponseTypeDef * SOAP_FMAC2 soap_instantiate__ns1__messageResponseTypeDef(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:202 */
#ifndef SOAP_TYPE__ns1__CAPHeaderTypeDef
#define SOAP_TYPE__ns1__CAPHeaderTypeDef (35)
/* complex XML schema type 'ns1:CAPHeaderTypeDef': */
class SOAP_CMAC _ns1__CAPHeaderTypeDef {
      public:
        /// Optional element 'ns1:logonUser' of XML schema type 'xsd:string'
        std::string *logonUser;
        /// Optional element 'ns1:logonCogId' of XML schema type 'xsd:int'
        int *logonCogId;
        /// Context that manages this object
        struct soap *soap;
      public:
        /// Return unique type id SOAP_TYPE__ns1__CAPHeaderTypeDef
        virtual long soap_type(void) const { return SOAP_TYPE__ns1__CAPHeaderTypeDef; }
        /// (Re)set members to default values
        virtual void soap_default(struct soap*);
        /// Serialize object to prepare for SOAP 1.1/1.2 encoded output (or with SOAP_XML_GRAPH) by analyzing its (cyclic) structures
        virtual void soap_serialize(struct soap*) const;
        /// Output object in XML, compliant with SOAP 1.1 encoding style, return error code or SOAP_OK
        virtual int soap_put(struct soap*, const char *tag, const char *type) const;
        /// Output object in XML, with tag and optional id attribute and xsi:type, return error code or SOAP_OK
        virtual int soap_out(struct soap*, const char *tag, int id, const char *type) const;
        /// Get object from XML, compliant with SOAP 1.1 encoding style, return pointer to object or NULL on error
        virtual void *soap_get(struct soap*, const char *tag, const char *type);
        /// Get object from XML, with matching tag and type (NULL matches any tag and type), return pointer to object or NULL on error
        virtual void *soap_in(struct soap*, const char *tag, const char *type);
        /// Return a new object of type _ns1__CAPHeaderTypeDef, default initialized and not managed by a soap context
        virtual _ns1__CAPHeaderTypeDef *soap_alloc(void) const { return SOAP_NEW_UNMANAGED(_ns1__CAPHeaderTypeDef); }
      public:
        /// Constructor with default initializations
        _ns1__CAPHeaderTypeDef() : logonUser(), logonCogId(), soap() { }
        virtual ~_ns1__CAPHeaderTypeDef() { }
        /// Friend allocator used by soap_new__ns1__CAPHeaderTypeDef(struct soap*, int)
        friend SOAP_FMAC1 _ns1__CAPHeaderTypeDef * SOAP_FMAC2 soap_instantiate__ns1__CAPHeaderTypeDef(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:960 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (86)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** MustUnderstand */
        _ns1__CAPHeaderTypeDef *ns1__CAPHeaderTypeDef;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() : ns1__CAPHeaderTypeDef() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* cap.h:983 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (88)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        /** Optional element 'ns1:CAPServiceException' of XML schema type 'ns1:CAPServiceException' */
        _ns1__CAPServiceException *ns1__CAPServiceException;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure throught this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
        char *__any;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : ns1__CAPServiceException(), __type(), fault(), __any() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* cap.h:1076 */
#ifndef SOAP_TYPE___ns1__getRequest
#define SOAP_TYPE___ns1__getRequest (94)
/* Wrapper: */
struct SOAP_CMAC __ns1__getRequest {
      public:
        /** Optional element 'ns1:getRequestTypeDef' of XML schema type 'ns2:requestParameterList' */
        ns2__requestParameterList *ns1__getRequestTypeDef;
      public:
        /** Return unique type id SOAP_TYPE___ns1__getRequest */
        long soap_type() const { return SOAP_TYPE___ns1__getRequest; }
        /** Constructor with member initializations */
        __ns1__getRequest() : ns1__getRequestTypeDef() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __ns1__getRequest * SOAP_FMAC2 soap_instantiate___ns1__getRequest(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:1153 */
#ifndef SOAP_TYPE___ns1__postCAP
#define SOAP_TYPE___ns1__postCAP (98)
/* Wrapper: */
struct SOAP_CMAC __ns1__postCAP {
      public:
        /** Optional element 'ns1:postCAPRequestTypeDef' of XML schema type 'ns1:postCAPRequestTypeDef' */
        _ns1__postCAPRequestTypeDef *ns1__postCAPRequestTypeDef;
      public:
        /** Return unique type id SOAP_TYPE___ns1__postCAP */
        long soap_type() const { return SOAP_TYPE___ns1__postCAP; }
        /** Constructor with member initializations */
        __ns1__postCAP() : ns1__postCAPRequestTypeDef() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __ns1__postCAP * SOAP_FMAC2 soap_instantiate___ns1__postCAP(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* cap.h:1230 */
#ifndef SOAP_TYPE___ns1__getMessage
#define SOAP_TYPE___ns1__getMessage (102)
/* Wrapper: */
struct SOAP_CMAC __ns1__getMessage {
      public:
        /** Optional element 'ns1:getMessageTypeDef' of XML schema type 'ns2:requestParameterList' */
        ns2__requestParameterList *ns1__getMessageTypeDef;
      public:
        /** Return unique type id SOAP_TYPE___ns1__getMessage */
        long soap_type() const { return SOAP_TYPE___ns1__getMessage; }
        /** Constructor with member initializations */
        __ns1__getMessage() : ns1__getMessageTypeDef() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __ns1__getMessage * SOAP_FMAC2 soap_instantiate___ns1__getMessage(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (7)
typedef char *_QName;
#endif

/* cap.h:163 */
#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (11)
typedef std::string xsd__anyURI;
#endif

/* cap.h:166 */
#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (12)
typedef std::string xsd__decimal;
#endif

/* cap.h:169 */
#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (13)
typedef std::string xsd__integer;
#endif

/* cap.h:172 */
#ifndef SOAP_TYPE_xsd__language
#define SOAP_TYPE_xsd__language (14)
typedef std::string xsd__language;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (4)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* time_t has binding name 'dateTime' for type 'xsd:dateTime' */
#ifndef SOAP_TYPE_dateTime
#define SOAP_TYPE_dateTime (41)
#endif

/* enum _ns22__alert_info_certainty has binding name '_ns22__alert_info_certainty' for type 'ns22:alert-info-certainty' */
#ifndef SOAP_TYPE__ns22__alert_info_certainty
#define SOAP_TYPE__ns22__alert_info_certainty (61)
#endif

/* enum _ns22__alert_info_severity has binding name '_ns22__alert_info_severity' for type 'ns22:alert-info-severity' */
#ifndef SOAP_TYPE__ns22__alert_info_severity
#define SOAP_TYPE__ns22__alert_info_severity (59)
#endif

/* enum _ns22__alert_info_urgency has binding name '_ns22__alert_info_urgency' for type 'ns22:alert-info-urgency' */
#ifndef SOAP_TYPE__ns22__alert_info_urgency
#define SOAP_TYPE__ns22__alert_info_urgency (57)
#endif

/* enum _ns22__alert_info_responseType has binding name '_ns22__alert_info_responseType' for type 'ns22:alert-info-responseType' */
#ifndef SOAP_TYPE__ns22__alert_info_responseType
#define SOAP_TYPE__ns22__alert_info_responseType (54)
#endif

/* enum _ns22__alert_info_category has binding name '_ns22__alert_info_category' for type 'ns22:alert-info-category' */
#ifndef SOAP_TYPE__ns22__alert_info_category
#define SOAP_TYPE__ns22__alert_info_category (51)
#endif

/* enum _ns22__alert_scope has binding name '_ns22__alert_scope' for type 'ns22:alert-scope' */
#ifndef SOAP_TYPE__ns22__alert_scope
#define SOAP_TYPE__ns22__alert_scope (46)
#endif

/* enum _ns22__alert_msgType has binding name '_ns22__alert_msgType' for type 'ns22:alert-msgType' */
#ifndef SOAP_TYPE__ns22__alert_msgType
#define SOAP_TYPE__ns22__alert_msgType (44)
#endif

/* enum _ns22__alert_status has binding name '_ns22__alert_status' for type 'ns22:alert-status' */
#ifndef SOAP_TYPE__ns22__alert_status
#define SOAP_TYPE__ns22__alert_status (42)
#endif

/* _ns22__alert_info_area_geocode has binding name '_ns22__alert_info_area_geocode' for type '' */
#ifndef SOAP_TYPE__ns22__alert_info_area_geocode
#define SOAP_TYPE__ns22__alert_info_area_geocode (77)
#endif

/* _ns22__alert_info_area has binding name '_ns22__alert_info_area' for type '' */
#ifndef SOAP_TYPE__ns22__alert_info_area
#define SOAP_TYPE__ns22__alert_info_area (75)
#endif

/* _ns22__alert_info_resource has binding name '_ns22__alert_info_resource' for type '' */
#ifndef SOAP_TYPE__ns22__alert_info_resource
#define SOAP_TYPE__ns22__alert_info_resource (71)
#endif

/* _ns22__alert_info_parameter has binding name '_ns22__alert_info_parameter' for type '' */
#ifndef SOAP_TYPE__ns22__alert_info_parameter
#define SOAP_TYPE__ns22__alert_info_parameter (68)
#endif

/* _ns22__alert_info_eventCode has binding name '_ns22__alert_info_eventCode' for type '' */
#ifndef SOAP_TYPE__ns22__alert_info_eventCode
#define SOAP_TYPE__ns22__alert_info_eventCode (63)
#endif

/* _ns22__alert_info has binding name '_ns22__alert_info' for type '' */
#ifndef SOAP_TYPE__ns22__alert_info
#define SOAP_TYPE__ns22__alert_info (48)
#endif

/* _ns1__CAPHeaderTypeDef has binding name '_ns1__CAPHeaderTypeDef' for type '' */
#ifndef SOAP_TYPE__ns1__CAPHeaderTypeDef
#define SOAP_TYPE__ns1__CAPHeaderTypeDef (35)
#endif

/* _ns1__messageResponseTypeDef has binding name '_ns1__messageResponseTypeDef' for type '' */
#ifndef SOAP_TYPE__ns1__messageResponseTypeDef
#define SOAP_TYPE__ns1__messageResponseTypeDef (33)
#endif

/* _ns1__postCAPResponseTypeDef has binding name '_ns1__postCAPResponseTypeDef' for type '' */
#ifndef SOAP_TYPE__ns1__postCAPResponseTypeDef
#define SOAP_TYPE__ns1__postCAPResponseTypeDef (31)
#endif

/* _ns1__CAPServiceException has binding name '_ns1__CAPServiceException' for type '' */
#ifndef SOAP_TYPE__ns1__CAPServiceException
#define SOAP_TYPE__ns1__CAPServiceException (29)
#endif

/* _ns1__postCAPRequestTypeDef has binding name '_ns1__postCAPRequestTypeDef' for type '' */
#ifndef SOAP_TYPE__ns1__postCAPRequestTypeDef
#define SOAP_TYPE__ns1__postCAPRequestTypeDef (27)
#endif

/* _ns22__alert has binding name '_ns22__alert' for type '' */
#ifndef SOAP_TYPE__ns22__alert
#define SOAP_TYPE__ns22__alert (25)
#endif

/* _ns3__parameterListItem has binding name '_ns3__parameterListItem' for type '' */
#ifndef SOAP_TYPE__ns3__parameterListItem
#define SOAP_TYPE__ns3__parameterListItem (23)
#endif

/* ns3__subParameterListItem has binding name 'ns3__subParameterListItem' for type 'ns3:subParameterListItem' */
#ifndef SOAP_TYPE_ns3__subParameterListItem
#define SOAP_TYPE_ns3__subParameterListItem (21)
#endif

/* ns3__responseParameterList has binding name 'ns3__responseParameterList' for type 'ns3:responseParameterList' */
#ifndef SOAP_TYPE_ns3__responseParameterList
#define SOAP_TYPE_ns3__responseParameterList (19)
#endif

/* ns2__parameterListItem has binding name 'ns2__parameterListItem' for type 'ns2:parameterListItem' */
#ifndef SOAP_TYPE_ns2__parameterListItem
#define SOAP_TYPE_ns2__parameterListItem (17)
#endif

/* ns2__requestParameterList has binding name 'ns2__requestParameterList' for type 'ns2:requestParameterList' */
#ifndef SOAP_TYPE_ns2__requestParameterList
#define SOAP_TYPE_ns2__requestParameterList (15)
#endif

/* xsd__language has binding name 'xsd__language' for type 'xsd:language' */
#ifndef SOAP_TYPE_xsd__language
#define SOAP_TYPE_xsd__language (14)
#endif

/* xsd__integer has binding name 'xsd__integer' for type 'xsd:integer' */
#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (13)
#endif

/* xsd__decimal has binding name 'xsd__decimal' for type 'xsd:decimal' */
#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (12)
#endif

/* xsd__anyURI has binding name 'xsd__anyURI' for type 'xsd:anyURI' */
#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (11)
#endif

/* std::string has binding name 'std__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (9)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (88)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (86)
#endif

/* struct __ns1__getMessage * has binding name 'PointerTo__ns1__getMessage' for type '-ns1:getMessage' */
#ifndef SOAP_TYPE_PointerTo__ns1__getMessage
#define SOAP_TYPE_PointerTo__ns1__getMessage (103)
#endif

/* struct __ns1__postCAP * has binding name 'PointerTo__ns1__postCAP' for type '-ns1:postCAP' */
#ifndef SOAP_TYPE_PointerTo__ns1__postCAP
#define SOAP_TYPE_PointerTo__ns1__postCAP (99)
#endif

/* struct __ns1__getRequest * has binding name 'PointerTo__ns1__getRequest' for type '-ns1:getRequest' */
#ifndef SOAP_TYPE_PointerTo__ns1__getRequest
#define SOAP_TYPE_PointerTo__ns1__getRequest (95)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (89)
#endif

/* struct SOAP_ENV__Header * has binding name 'PointerToSOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Header
#define SOAP_TYPE_PointerToSOAP_ENV__Header (87)
#endif

/* int * has binding name 'PointerToint' for type 'xsd:int' */
#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (85)
#endif

/* std::string * has binding name 'PointerToxsd__decimal' for type 'xsd:decimal' */
#ifndef SOAP_TYPE_PointerToxsd__decimal
#define SOAP_TYPE_PointerToxsd__decimal (80)
#endif

/* _ns22__alert_info_area_geocode * has binding name 'PointerTo_ns22__alert_info_area_geocode' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_area_geocode
#define SOAP_TYPE_PointerTo_ns22__alert_info_area_geocode (78)
#endif

/* _ns22__alert_info_area * has binding name 'PointerTo_ns22__alert_info_area' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_area
#define SOAP_TYPE_PointerTo_ns22__alert_info_area (76)
#endif

/* std::string * has binding name 'PointerToxsd__integer' for type 'xsd:integer' */
#ifndef SOAP_TYPE_PointerToxsd__integer
#define SOAP_TYPE_PointerToxsd__integer (73)
#endif

/* _ns22__alert_info_resource * has binding name 'PointerTo_ns22__alert_info_resource' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_resource
#define SOAP_TYPE_PointerTo_ns22__alert_info_resource (72)
#endif

/* _ns22__alert_info_parameter * has binding name 'PointerTo_ns22__alert_info_parameter' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_parameter
#define SOAP_TYPE_PointerTo_ns22__alert_info_parameter (69)
#endif

/* std::string * has binding name 'PointerToxsd__anyURI' for type 'xsd:anyURI' */
#ifndef SOAP_TYPE_PointerToxsd__anyURI
#define SOAP_TYPE_PointerToxsd__anyURI (67)
#endif

/* time_t * has binding name 'PointerTodateTime' for type 'xsd:dateTime' */
#ifndef SOAP_TYPE_PointerTodateTime
#define SOAP_TYPE_PointerTodateTime (66)
#endif

/* _ns22__alert_info_eventCode * has binding name 'PointerTo_ns22__alert_info_eventCode' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_eventCode
#define SOAP_TYPE_PointerTo_ns22__alert_info_eventCode (64)
#endif

/* enum _ns22__alert_info_certainty * has binding name 'PointerTo_ns22__alert_info_certainty' for type 'ns22:alert-info-certainty' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_certainty
#define SOAP_TYPE_PointerTo_ns22__alert_info_certainty (62)
#endif

/* enum _ns22__alert_info_severity * has binding name 'PointerTo_ns22__alert_info_severity' for type 'ns22:alert-info-severity' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_severity
#define SOAP_TYPE_PointerTo_ns22__alert_info_severity (60)
#endif

/* enum _ns22__alert_info_urgency * has binding name 'PointerTo_ns22__alert_info_urgency' for type 'ns22:alert-info-urgency' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_urgency
#define SOAP_TYPE_PointerTo_ns22__alert_info_urgency (58)
#endif

/* enum _ns22__alert_info_responseType * has binding name 'PointerTo_ns22__alert_info_responseType' for type 'ns22:alert-info-responseType' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_responseType
#define SOAP_TYPE_PointerTo_ns22__alert_info_responseType (55)
#endif

/* enum _ns22__alert_info_category * has binding name 'PointerTo_ns22__alert_info_category' for type 'ns22:alert-info-category' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info_category
#define SOAP_TYPE_PointerTo_ns22__alert_info_category (52)
#endif

/* std::string * has binding name 'PointerToxsd__language' for type 'xsd:language' */
#ifndef SOAP_TYPE_PointerToxsd__language
#define SOAP_TYPE_PointerToxsd__language (50)
#endif

/* _ns22__alert_info * has binding name 'PointerTo_ns22__alert_info' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_info
#define SOAP_TYPE_PointerTo_ns22__alert_info (49)
#endif

/* enum _ns22__alert_scope * has binding name 'PointerTo_ns22__alert_scope' for type 'ns22:alert-scope' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_scope
#define SOAP_TYPE_PointerTo_ns22__alert_scope (47)
#endif

/* enum _ns22__alert_msgType * has binding name 'PointerTo_ns22__alert_msgType' for type 'ns22:alert-msgType' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_msgType
#define SOAP_TYPE_PointerTo_ns22__alert_msgType (45)
#endif

/* enum _ns22__alert_status * has binding name 'PointerTo_ns22__alert_status' for type 'ns22:alert-status' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert_status
#define SOAP_TYPE_PointerTo_ns22__alert_status (43)
#endif

/* _ns1__CAPHeaderTypeDef * has binding name 'PointerTo_ns1__CAPHeaderTypeDef' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__CAPHeaderTypeDef
#define SOAP_TYPE_PointerTo_ns1__CAPHeaderTypeDef (36)
#endif

/* _ns1__messageResponseTypeDef * has binding name 'PointerTo_ns1__messageResponseTypeDef' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__messageResponseTypeDef
#define SOAP_TYPE_PointerTo_ns1__messageResponseTypeDef (34)
#endif

/* _ns1__postCAPResponseTypeDef * has binding name 'PointerTo_ns1__postCAPResponseTypeDef' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__postCAPResponseTypeDef
#define SOAP_TYPE_PointerTo_ns1__postCAPResponseTypeDef (32)
#endif

/* _ns1__CAPServiceException * has binding name 'PointerTo_ns1__CAPServiceException' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__CAPServiceException
#define SOAP_TYPE_PointerTo_ns1__CAPServiceException (30)
#endif

/* _ns1__postCAPRequestTypeDef * has binding name 'PointerTo_ns1__postCAPRequestTypeDef' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns1__postCAPRequestTypeDef
#define SOAP_TYPE_PointerTo_ns1__postCAPRequestTypeDef (28)
#endif

/* _ns22__alert * has binding name 'PointerTo_ns22__alert' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns22__alert
#define SOAP_TYPE_PointerTo_ns22__alert (26)
#endif

/* _ns3__parameterListItem * has binding name 'PointerTo_ns3__parameterListItem' for type '' */
#ifndef SOAP_TYPE_PointerTo_ns3__parameterListItem
#define SOAP_TYPE_PointerTo_ns3__parameterListItem (24)
#endif

/* ns3__subParameterListItem * has binding name 'PointerTons3__subParameterListItem' for type 'ns3:subParameterListItem' */
#ifndef SOAP_TYPE_PointerTons3__subParameterListItem
#define SOAP_TYPE_PointerTons3__subParameterListItem (22)
#endif

/* ns3__responseParameterList * has binding name 'PointerTons3__responseParameterList' for type 'ns3:responseParameterList' */
#ifndef SOAP_TYPE_PointerTons3__responseParameterList
#define SOAP_TYPE_PointerTons3__responseParameterList (20)
#endif

/* ns2__parameterListItem * has binding name 'PointerTons2__parameterListItem' for type 'ns2:parameterListItem' */
#ifndef SOAP_TYPE_PointerTons2__parameterListItem
#define SOAP_TYPE_PointerTons2__parameterListItem (18)
#endif

/* ns2__requestParameterList * has binding name 'PointerTons2__requestParameterList' for type 'ns2:requestParameterList' */
#ifndef SOAP_TYPE_PointerTons2__requestParameterList
#define SOAP_TYPE_PointerTons2__requestParameterList (16)
#endif

/* std::string * has binding name 'PointerTostd__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (10)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (7)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (5)
#endif

/* std::vector<_ns22__alert *>  has binding name 'std__vectorTemplateOfPointerTo_ns22__alert' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTo_ns22__alert
#define SOAP_TYPE_std__vectorTemplateOfPointerTo_ns22__alert (84)
#endif

/* std::vector<char *>  has binding name 'std__vectorTemplateOf_XML' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_XML
#define SOAP_TYPE_std__vectorTemplateOf_XML (83)
#endif

/* std::vector<_ns22__alert_info>  has binding name 'std__vectorTemplateOf_ns22__alert_info' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info (82)
#endif

/* std::vector<_ns22__alert_info_area>  has binding name 'std__vectorTemplateOf_ns22__alert_info_area' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_area
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_area (81)
#endif

/* std::vector<_ns22__alert_info_area_geocode>  has binding name 'std__vectorTemplateOf_ns22__alert_info_area_geocode' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_area_geocode
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_area_geocode (79)
#endif

/* std::vector<_ns22__alert_info_resource>  has binding name 'std__vectorTemplateOf_ns22__alert_info_resource' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_resource
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_resource (74)
#endif

/* std::vector<_ns22__alert_info_parameter>  has binding name 'std__vectorTemplateOf_ns22__alert_info_parameter' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_parameter
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_parameter (70)
#endif

/* std::vector<_ns22__alert_info_eventCode>  has binding name 'std__vectorTemplateOf_ns22__alert_info_eventCode' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_eventCode
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_eventCode (65)
#endif

/* std::vector<enum _ns22__alert_info_responseType>  has binding name 'std__vectorTemplateOf_ns22__alert_info_responseType' for type 'ns22:alert-info-responseType' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_responseType
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_responseType (56)
#endif

/* std::vector<enum _ns22__alert_info_category>  has binding name 'std__vectorTemplateOf_ns22__alert_info_category' for type 'ns22:alert-info-category' */
#ifndef SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_category
#define SOAP_TYPE_std__vectorTemplateOf_ns22__alert_info_category (53)
#endif

/* std::vector<ns3__subParameterListItem *>  has binding name 'std__vectorTemplateOfPointerTons3__subParameterListItem' for type 'ns3:subParameterListItem' */
#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons3__subParameterListItem
#define SOAP_TYPE_std__vectorTemplateOfPointerTons3__subParameterListItem (40)
#endif

/* std::vector<_ns3__parameterListItem *>  has binding name 'std__vectorTemplateOfPointerTo_ns3__parameterListItem' for type '' */
#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTo_ns3__parameterListItem
#define SOAP_TYPE_std__vectorTemplateOfPointerTo_ns3__parameterListItem (39)
#endif

/* std::vector<std::string>  has binding name 'std__vectorTemplateOfstd__string' for type 'xsd:string' */
#ifndef SOAP_TYPE_std__vectorTemplateOfstd__string
#define SOAP_TYPE_std__vectorTemplateOfstd__string (38)
#endif

/* std::vector<ns2__parameterListItem *>  has binding name 'std__vectorTemplateOfPointerTons2__parameterListItem' for type 'ns2:parameterListItem' */
#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons2__parameterListItem
#define SOAP_TYPE_std__vectorTemplateOfPointerTons2__parameterListItem (37)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of soapStub.h */
