/* soapCAPSoapHttpProxy.h
   Generated by gSOAP 2.8.75 for cap.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapCAPSoapHttpProxy_H
#define soapCAPSoapHttpProxy_H
#include "soapH.h"

    class SOAP_CMAC CAPSoapHttpProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'CAPSoapHttpProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in cap.h, if any
        /// Construct a proxy with new managing context
        CAPSoapHttpProxy();
        /// Copy constructor
        CAPSoapHttpProxy(const CAPSoapHttpProxy& rhs);
        /// Construct proxy given a shared managing context
        CAPSoapHttpProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        CAPSoapHttpProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        CAPSoapHttpProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        CAPSoapHttpProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        CAPSoapHttpProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        CAPSoapHttpProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the contructor
        virtual ~CAPSoapHttpProxy();
        /// Initializer used by constructors
        virtual void CAPSoapHttpProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual CAPSoapHttpProxy *copy();
        /// Copy assignment
        CAPSoapHttpProxy& operator=(const CAPSoapHttpProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(_ns2__CAPHeaderTypeDef *ns2__CAPHeaderTypeDef);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'getRequest' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getRequest(ns3__requestParameterList *ns2__getRequestTypeDef, ns4__responseParameterList &ns2__getResponseTypeDef) { return this->getRequest(NULL, NULL, ns2__getRequestTypeDef, ns2__getResponseTypeDef); }
        /// Web service synchronous operation 'getRequest' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getRequest(const char *soap_endpoint_url, const char *soap_action, ns3__requestParameterList *ns2__getRequestTypeDef, ns4__responseParameterList &ns2__getResponseTypeDef) { return this->send_getRequest(soap_endpoint_url, soap_action, ns2__getRequestTypeDef) || this->recv_getRequest(ns2__getResponseTypeDef) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getRequest' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getRequest(const char *soap_endpoint_url, const char *soap_action, ns3__requestParameterList *ns2__getRequestTypeDef);
        /// Web service asynchronous operation 'recv_getRequest' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getRequest(ns4__responseParameterList &ns2__getResponseTypeDef);
        //
        /// Web service synchronous operation 'postCAP' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int postCAP(_ns2__postCAPRequestTypeDef *ns2__postCAPRequestTypeDef, _ns2__postCAPResponseTypeDef &ns2__postCAPResponseTypeDef) { return this->postCAP(NULL, NULL, ns2__postCAPRequestTypeDef, ns2__postCAPResponseTypeDef); }
        /// Web service synchronous operation 'postCAP' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int postCAP(const char *soap_endpoint_url, const char *soap_action, _ns2__postCAPRequestTypeDef *ns2__postCAPRequestTypeDef, _ns2__postCAPResponseTypeDef &ns2__postCAPResponseTypeDef) { return this->send_postCAP(soap_endpoint_url, soap_action, ns2__postCAPRequestTypeDef) || this->recv_postCAP(ns2__postCAPResponseTypeDef) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_postCAP' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_postCAP(const char *soap_endpoint_url, const char *soap_action, _ns2__postCAPRequestTypeDef *ns2__postCAPRequestTypeDef);
        /// Web service asynchronous operation 'recv_postCAP' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_postCAP(_ns2__postCAPResponseTypeDef &ns2__postCAPResponseTypeDef);
        //
        /// Web service synchronous operation 'getMessage' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int getMessage(ns3__requestParameterList *ns2__getMessageTypeDef, _ns2__messageResponseTypeDef &ns2__messageResponseTypeDef) { return this->getMessage(NULL, NULL, ns2__getMessageTypeDef, ns2__messageResponseTypeDef); }
        /// Web service synchronous operation 'getMessage' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int getMessage(const char *soap_endpoint_url, const char *soap_action, ns3__requestParameterList *ns2__getMessageTypeDef, _ns2__messageResponseTypeDef &ns2__messageResponseTypeDef) { return this->send_getMessage(soap_endpoint_url, soap_action, ns2__getMessageTypeDef) || this->recv_getMessage(ns2__messageResponseTypeDef) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_getMessage' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_getMessage(const char *soap_endpoint_url, const char *soap_action, ns3__requestParameterList *ns2__getMessageTypeDef);
        /// Web service asynchronous operation 'recv_getMessage' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_getMessage(_ns2__messageResponseTypeDef &ns2__messageResponseTypeDef);
    };
#endif
